name: "hl-multilib-v2 Repository Update"
on:
  push:
  schedule:
    - cron: '17 */12 * * *' # “At minute 17 past every 12th hour.”
  workflow_dispatch:

env:
  CFLAGS: "-march=x86-64-v2 -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection"

jobs:
  build-lib32-amf-amdgpu-pro-fix:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      PKGDEST: /tmp/hl-multilib-v2
      repo: "hl-multilib-v2"
      arch_repo: "x86_64_v2"

    steps:
      - name: "Install Git"
        run: pacman -Syu --noconfirm git

      - name: "Checkout PKGBUILDs"
        run: |
            git clone https://aur.archlinux.org/amdgpu-pro-installer-fix.git
            cd /__w/hl-repo/hl-repo/amdgpu-pro-installer-fix

      - name: "Prepare for makepkg"
        run: |
            pacman -Syu --noconfirm base-devel sudo wget sshpass
            useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            chown user -R ..
            chown user -R /tmp
            sed -i 's/#PACKAGER=""/PACKAGER="${{ secrets.PACKAGER }}"/g' /etc/makepkg.conf
            sed -i 's/#GPGKEY=""/GPGKEY="${{ secrets.GPG_KEY }}"/g' /etc/makepkg.conf
      
      - name: "Build amf-amdgpu-pro-fix"
        run: |
            su user -c "yes '' | makepkg --noconfirm -s"
      
      - name: "Upload to repo"
        run: |
            cd $PKGDEST
            rm -rfv amdgpu-pro-libgl-fix*.pkg.tar.zst amf-amdgpu-pro-fix*.pkg.tar.zst vulkan-amdgpu-pro-fix*.pkg.tar.zst
            wget https://osdn.net/projects/hybridlinux/storage/$repo/$arch_repo/$repo.db.tar.gz https://osdn.net/projects/hybridlinux/storage/$repo/$arch_repo/$repo.files.tar.gz
            sudo repo-add $repo.db.tar.gz *.pkg.tar.zst
            echo -e "${{ secrets.PRIVATE_SSH_KEY }}" > /tmp/tmp_id
            chmod 600 /tmp/tmp_id
            echo "Upload to SourceForge Mirror"
            scp -O -v -P 22 -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -i /tmp/tmp_id $PKGDEST/* ${{ secrets.SOURCEFORGE_USERNAME }}@${{ secrets.SOURCEFORGE_HOST }}:/home/pfs/project/hybridlinux/Repo/$repo/$arch_repo
            echo "Upload to OSDN Mirror"
            scp -O -v -P 22 -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -i /tmp/tmp_id $PKGDEST/* ${{ secrets.OSDN_USERNAME }}@${{ secrets.OSDN_HOST }}:/storage/groups/h/hy/hybridlinux/$repo/$arch_repo

  build-lib32-mesa-tkg:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      PKGDEST: /tmp/hl-multilib-v2
      repo: "hl-multilib-v2"
      arch_repo: "x86_64_v2"
      _compiler: "clang"
      _no_lto: "true"
      _additional_meson_flags_64: "-march=x86-64-v2 -Dgallium-rusticl=true -Dopencl-spirv=true -Dshader-cache=true -Dllvm=true"
      MESA_WHICH_LLVM: "3"

    needs: [ build-lib32-amf-amdgpu-pro-fix ]

    steps:
      - name: "Checkout PKGBUILDs from Github"
        run: |
            git clone https://github.com/Frogging-Family/mesa-git.git
            cd /__w/hl-repo/hl-repo/mesa-git

      - name: "Prepare for makepkg"
        run: |
            pacman -Syu --noconfirm base-devel sudo wget sshpass
            useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            chown user -R ..
            chown user -R /tmp
            sed -i 's/#PACKAGER=""/PACKAGER="${{ secrets.PACKAGER }}"/g' /etc/makepkg.conf
            sed -i 's/#GPGKEY=""/GPGKEY="${{ secrets.GPG_KEY }}"/g' /etc/makepkg.conf

      - name: "Build mesa-tkg-git"
        run: |
            su user -c "yes '' | makepkg --noconfirm -s"

      - name: "Upload to repo"
        run: |
            cd $PKGDEST
            rm -rfv mesa-tkg-git*.pkg.tar.zst
            wget https://osdn.net/projects/hybridlinux/storage/$repo/$arch_repo/$repo.db.tar.gz https://osdn.net/projects/hybridlinux/storage/$repo/$arch_repo/$repo.files.tar.gz
            sudo repo-add $repo.db.tar.gz *.pkg.tar.zst
            echo -e "${{ secrets.PRIVATE_SSH_KEY }}" > /tmp/tmp_id
            chmod 600 /tmp/tmp_id
            echo "Upload to SourceForge Mirror"
            scp -O -v -P 22 -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -i /tmp/tmp_id $PKGDEST/* ${{ secrets.SOURCEFORGE_USERNAME }}@${{ secrets.SOURCEFORGE_HOST }}:/home/pfs/project/hybridlinux/Repo/$repo/$arch_repo
            echo "Upload to OSDN Mirror"
            scp -O -v -P 22 -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -i /tmp/tmp_id $PKGDEST/* ${{ secrets.OSDN_USERNAME }}@${{ secrets.OSDN_HOST }}:/storage/groups/h/hy/hybridlinux/$repo/$arch_repo
